# Default values for task7-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: 345070817929.dkr.ecr.eu-west-1.amazonaws.com/mvs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "counter"
  containerPort: 8080
  volumeMounts:
    mountPath: /data

volume:
  name: counter-pv-storage
  claimName: counter-pvc

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

cronjob:
  schedule: "*/1 * * * *"
  image:
    repository: 345070817929.dkr.ecr.eu-west-1.amazonaws.com/mvs
    tag: "print-hour"
    pullPolicy: IfNotPresent
  restartPolicy: OnFailure

pvc:
  accesMode: ReadWriteOnce
  storage: 1Gi