apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pkiaasrnd-test-mvs
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
