kind: PersistentVolume
apiVersion: v1
metadata:
  name: counter-pv
  labels:
    type: local
spec:
  storageClassName: counter-sc
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/vidalm1/git/src/MarVidal17/Entrust-initial/7task"