apiVersion: v1
kind: Service
metadata:
  name: counter-service
  labels:
    app: counter
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: counter
