apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print-hour
            image: print-hour:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure